CREATE TABLE [dbo].[PACIENTES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRES] [varchar](25) NOT NULL,
	[APELLIDOS] [varchar](25) NOT NULL,
	[DNI] [char](8) NULL,
	[DIRECCION] [varchar](100) NOT NULL,
	[TELEFONO] [varchar](25) NOT NULL,
	[SEXO] [char](1) NOT NULL,
	[FECHANACIMIENTO] [date] NOT NULL,
	[FECHAREGISTRO] [datetime] NULL,
	[FECHAMODIFICACION] [datetime] NULL,
	[ACTIVO] [bit] NOT NULL,
 CONSTRAINT [PK_PACIENTES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[MEDICOS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRES] [varchar](25) NOT NULL,
	[APELLIDOS] [varchar](25) NOT NULL,
	[DNI] [char](8) NOT NULL,
	[DIRECCION] [varchar](100) NOT NULL,
	[CORREO] [nvarchar](50) NOT NULL,
	[TELEFONO] [varchar](25) NULL,
	[SEXO] [char](1) NOT NULL,
	[NUMCOLEGIATURA] [varchar](10) NOT NULL,
	[FECHANACIMIENTO] [date] NOT NULL,
	[FECHAREGISTRO] [datetime] NULL,
	[FECHAMODIFICACION] [datetime] NULL,
	[USUARIOREGISTRO] [varchar](25) NULL,
	[ACTIVO] [bit] NOT NULL,
 CONSTRAINT [PK_MEDICOS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[CITAS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MEDICOID] [int] NOT NULL,
	[PACIENTEID] [int] NOT NULL,
	[FECHAATENCION] [date] NOT NULL,
	[INICIOATENCION] [time](7) NOT NULL,
	[FINATENCION] [time](7) NOT NULL,
	[ESTADO] [varchar](25) NOT NULL,
	[OBSERVACIONES] [varchar](500) NULL,
	[ACTIVO] [bit] NOT NULL,
	[FECHAREGISTRO] [datetime] NOT NULL,
	[USUARIOREGISTRO] [varchar](25) NULL,
	[FECHAMODIFICACION] [datetime] NULL,
	[USUARIOMODIFICACION] [varchar](25) NULL,
 CONSTRAINT [PK_CITAS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CITAS]  WITH CHECK ADD  CONSTRAINT [FK_MEDICOS_CITAS] FOREIGN KEY([MEDICOID])
REFERENCES [dbo].[MEDICOS] ([ID])
GO
ALTER TABLE [dbo].[CITAS]  WITH CHECK ADD  CONSTRAINT [FK_PACIENTES_CITAS] FOREIGN KEY([PACIENTEID])
REFERENCES [dbo].[PACIENTES] ([ID])

--------------------------------------------------------------------------------

alter table PACIENTES
add constraint PACIENTESConstraint default getdate() 
for FECHAREGISTRO
GO
alter table CITAS
add constraint CITASConstraint default getdate() 
for FECHAREGISTRO
GO
alter table MEDICOS
add constraint MEDICOSConstraint default getdate() 
for FECHAREGISTRO
GO